# Generated by Django 2.1 on 2019-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.IntegerField()),
                ('student_name', models.CharField(max_length=16)),
                ('student_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('exam_code', models.IntegerField()),
                ('target_grade', models.IntegerField()),
                ('exam_range', models.TextField(max_length=1000)),
                ('exam_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField(auto_now_add=True)),
                ('notice_title', models.CharField(max_length=30)),
                ('target_grade', models.IntegerField()),
                ('notice_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
