# Generated by Django 2.1 on 2019-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticedata',
            name='notice_image',
            field=models.ImageField(upload_to='notice/'),
        ),
    ]
