# Generated by Django 2.1 on 2019-02-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20190225_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=30)),
                ('file_description', models.TextField(blank=True, max_length=500, null=True)),
                ('file_document', models.FileField(upload_to='files/')),
            ],
        ),
    ]
