# Generated by Django 2.1 on 2019-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_filedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticedata',
            name='notice_kind',
            field=models.IntegerField(default=0),
        ),
    ]
