# Generated by Django 2.1 on 2019-03-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_noticedata_notice_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNoticeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=20)),
                ('notice_content', models.CharField(blank=True, max_length=200)),
                ('notice_image', models.ImageField(blank=True, null=True, upload_to='alertNotice/image/')),
                ('notice_file', models.FileField(blank=True, null=True, upload_to='alertNotice/files/')),
                ('notice_due_date', models.DateTimeField()),
            ],
        ),
    ]
