# Generated by Django 2.1 on 2019-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_alertnoticedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNBoardApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=7)),
                ('apply_target', models.IntegerField(default=0)),
                ('apply_content', models.TextField(max_length=2000)),
            ],
        ),
    ]
