# Generated by Django 2.1 on 2019-03-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_cnboardapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnoticedata',
            name='target_grade',
            field=models.IntegerField(default=0),
        ),
    ]
