# Generated by Django 2.1 on 2018-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateTimeField(auto_now_add=True)),
                ('meal_txt', models.CharField(max_length=250)),
                ('meal_time_part', models.IntegerField(default=0)),
            ],
        ),
    ]
