# Generated by Django 2.1 on 2019-02-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
        ('Meal', '0002_auto_20190223_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='related_likes_meal_comment', to='Service.CNUser'),
        ),
        migrations.AlterField(
            model_name='mealcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_author_meal_comment', to='Service.CNUser'),
        ),
    ]
